version: '3.8'

services:
  frontend:
    image: teht12
    ports:
      - 64791:5000
    networks:
      - app-network
  
  backend:
    image: teht13
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=messages
      - POSTGRES_USER=aappo
      - POSTGRES_PASSWORD=salaisuus
    networks:
      - app-network

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=messages
      - POSTGRES_USER=aappo
      - POSTGRES_PASSWORD=salaisuus
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
