version: '3.8'

services:
  frontend:
    image: teht12
    ports:
      - 64791:5000
  
  backend:
    image: teht13
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=messages
      - POSTGRES_USER=aappo
      - POSTGRES_PASSWORD=salaisuus

  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=messages
      - POSTGRES_USER=aappo
      - POSTGRES_PASSWORD=salaisuus
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: